server:
  port: 8082
spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
    integration:
      enabled: true
  application:
    name: orders-service
  cloud:
    config:
      uri: http://localhost:8088
  config:
    import: "optional:configserver:"

